### ISSUE TITLE
model DLA-60

### ISSUE THREAD

**Issue by aswa123** [zju3dv/snake#102]
I want change the backbone from DLA-34 to DLA-60.
I change it but still there is one error 
RuntimeError: Given groups=1, weight of size 64 128 1, expected input[9, 256, 40] to have 128 channels, but got 256 channels instead.

Can you please help me with this.

**Comment by pengsida** [comment]
Locate where the bug is and revise the code.

**Comment by aswa123** [comment]
Traceback (most recent call last):
  File "/home/hermes/Downloads/snake-master/train_net.py", line 54, in <module>
    main()
  File "/home/hermes/Downloads/snake-master/train_net.py", line 50, in main
    train(cfg, network)
  File "/home/hermes/Downloads/snake-master/train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/hermes/Downloads/snake-master/lib/train/trainers/trainer.py", line 38, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/snake.py", line 19, in forward
    output = self.net(batch['inp'], batch)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 33, in forward
    output = self.gcn(output, cnn_feature, batch)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/evolve.py", line 88, in forward
    ex_pred = self.init_poly(self.init_gcn, cnn_feature, init['i_it_4py'], init['c_it_4py'], init['4py_ind'])
  File "lib/networks/snake/evolve.py", line 61, in init_poly
    init_feature = self.fuse(init_feature)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 128 1, expected input[12, 256, 40] to have 128 channels, but got 256 channels instead

**Comment by pengsida** [comment]
File "lib/networks/snake/evolve.py", line 61, in init_poly

**Comment by aswa123** [comment]
Can you please tell me in brief ?

**Comment by pengsida** [comment]
init_feature = self.fuse(init_feature)

**Comment by aswa123** [comment]
Thank you for your reply but actually I'm trying to solve this error but still i stuck with same error.
RuntimeError: Given groups=1, weight of size 64 128 1, expected input[12, 256, 40] to have 128 channels, but got 256 channels instead
