### ISSUE TITLE
Change backbone dla34-dla60

### ISSUE THREAD

**Issue by aswa123** [zju3dv/snake#104]
I want to change the backbone. Can you please tell me where should I need to change?Thank you for your reply but actually I'm trying to solve this error but still i stuck with same error.

RuntimeError: Given groups=1, weight of size 64 128 1, expected input[12, 256, 40] to have 128 channels, but got 256 channels instead

**Comment by aswa123** [comment]
#pengsida

**Comment by pengsida** [comment]
The bug is caused by `File "lib/networks/snake/evolve.py", line 61, in init_poly`.
You could find the reason and revise the code.

**Comment by aswa123** [comment]
the line 61 is 
init_feature = self.fuse(init_feature)
and after I check self.fuse I got
self.fuse = nn.Conv1d(128, 64, 1) , line 12 , in evolve.py

**Comment by pengsida** [comment]
Change `nn.Conv1d(128, 64, 1)` to `nn.Conv1d(256, 64, 1)`.
Maybe you need to learn more about PyTorch or the network layers.

**Comment by aswa123** [comment]
I tried but then also I got this
RuntimeError: Given groups=1, weight of size 128 66 9, expected input[11, 130, 136] to have 66 channels, but got 130 channels instead

**Comment by pengsida** [comment]
There are another bugs.

**Comment by aswa123** [comment]
Traceback (most recent call last):
  File "/home/hermes/Downloads/snake-master/train_net.py", line 54, in <module>
    main()
  File "/home/hermes/Downloads/snake-master/train_net.py", line 50, in main
    train(cfg, network)
  File "/home/hermes/Downloads/snake-master/train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/hermes/Downloads/snake-master/lib/train/trainers/trainer.py", line 38, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/snake.py", line 19, in forward
    output = self.net(batch['inp'], batch)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 33, in forward
    output = self.gcn(output, cnn_feature, batch)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/evolve.py", line 94, in forward
    py_pred = self.evolve_poly(self.evolve_gcn, cnn_feature, init['i_it_py'], init['c_it_py'], init['py_ind'])
  File "lib/networks/snake/evolve.py", line 78, in evolve_poly
    i_poly = i_it_poly * snake_config.ro + snake(init_input, adj).permute(0, 2, 1)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/snake.py", line 79, in forward
    x = self.head(x, adj)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/snake.py", line 48, in forward
    x = self.conv(x, adj)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/snake.py", line 30, in forward
    return self.fc(input)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hermes/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 196, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 128 66 9, expected input[11, 130, 136] to have 66 channels, but got 130 channels instead

**Comment by pengsida** [comment]
File "lib/networks/snake/snake.py", line 48, in forward
