### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by zhaozebin1997** [zju3dv/snake#116]
thanks for your work. it's amazing.i follow your tips and met error.
(snake36) zhaozb@rtx4:~/projects/Snake$ python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml test.dataset CityscapesVal
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 51, in run_evaluate
    network = make_network(cfg).cuda()
  File "/home/zhaozb/projects/Snake/lib/networks/make_network.py", line 23, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "lib/networks/rcnn_snake/__init__.py", line 17, in get_network
    network = get_model(num_layers, heads, head_conv, snake_config.down_ratio, cfg.det_dir)
  File "lib/networks/rcnn_snake/ct_rcnn_snake.py", line 47, in get_network
    network = Network(num_layers, heads, head_conv, down_ratio, det_dir)
  File "lib/networks/rcnn_snake/ct_rcnn_snake.py", line 22, in __init__
    head_conv=head_conv)
  File "lib/networks/rcnn_snake/dla.py", line 432, in __init__
    self.base = globals()[base_name](pretrained=pretrained)
  File "lib/networks/rcnn_snake/dla.py", line 315, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "lib/networks/rcnn_snake/dla.py", line 301, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "/home/zhaozb/anaconda3/envs/snake36/lib/python3.6/site-packages/torch/hub.py", line 495, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/zhaozb/anaconda3/envs/snake36/lib/python3.6/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/zhaozb/anaconda3/envs/snake36/lib/python3.6/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by pengsida** [comment]
https://stackoverflow.com/questions/56391392/how-to-fix-pickle-unpicklingerror-invalid-load-key-error-in-pytorch

**Comment by zhaozebin1997** [comment]
thanks
