### ISSUE TITLE
the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCBlas.cu:425

### ISSUE THREAD

**Issue by PPPPWU** [zju3dv/snake#120]
index created!
  0%|                                                                                                                          | 0/7517 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 60, in run_evaluate
    output = network(inp)
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 54, in forward
    output, cnn_feature = self.dla(x)
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 470, in forward
    x = self.dla_up(x)
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 409, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 383, in forward
    layers[i] = upsample(project(layers[i]))
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 356, in forward
    x = self.conv(x)
  File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Snakes/lib/networks/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/mnt/Snakes/lib/networks/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCBlas.cu:425

**Comment by PPPPWU** [comment]
PyTorch Version: 1.1
OS: Windows 10
Python version: 3.6
CUDA: 9.0

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/77

**Comment by Fool-hash** [comment]
> index created!
> 0%| | 0/7517 [00:00<?, ?it/s]
> Traceback (most recent call last):
> File "run.py", line 99, in
> globals()'run_'+args.type
> File "run.py", line 60, in run_evaluate
> output = network(inp)
> File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "lib/networks/snake/ct_snake.py", line 54, in forward
> output, cnn_feature = self.dla(x)
> File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "lib/networks/snake/dla.py", line 470, in forward
> x = self.dla_up(x)
> File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "lib/networks/snake/dla.py", line 409, in forward
> ida(layers, len(layers) - i - 2, len(layers))
> File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "lib/networks/snake/dla.py", line 383, in forward
> layers[i] = upsample(project(layers[i]))
> File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "lib/networks/snake/dla.py", line 356, in forward
> x = self.conv(x)
> File "/root/miniconda3/envs/myconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/mnt/Snakes/lib/networks/dcn_v2.py", line 128, in forward
> self.deformable_groups)
> File "/mnt/Snakes/lib/networks/dcn_v2.py", line 31, in forward
> ctx.deformable_groups)
> RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCBlas.cu:425

I have the same problem. How did you solve it?

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/77
