### ISSUE TITLE
KeyError: 'segmentation'

### ISSUE THREAD

**Issue by Aaron-Ace** [zju3dv/snake#121]
python train_net.py --cfg_file configs/sbd_snake_test.yaml model costum
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
load model: data/model/snake/costum/4.pth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 28, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/aaronace/Downloads/snake-1/lib/train/trainers/trainer.py", line 32, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aaronace/Downloads/snake-1/lib/datasets/voc/snake.py", line 164, in __getitem__
    img, instance_polys, cls_ids = self.read_original_data(anno, path)
  File "/home/aaronace/Downloads/snake-1/lib/datasets/voc/snake.py", line 32, in read_original_data
    instance_polys = [[np.array(poly).reshape(-1, 2) for poly in obj['segmentation']] for obj in anno]
  File "/home/aaronace/Downloads/snake-1/lib/datasets/voc/snake.py", line 32, in <listcomp>
    instance_polys = [[np.array(poly).reshape(-1, 2) for poly in obj['segmentation']] for obj in anno]
KeyError: 'segmentation'

我遇到python train_net.py --cfg_file configs/sbd_snake_test.yaml model costum
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
load model: data/model/snake/costum/4.pth
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 28, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/aaronace/Downloads/snake-1/lib/train/trainers/trainer.py", line 32, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aaronace/anaconda3/envs/snake-1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aaronace/Downloads/snake-1/lib/datasets/voc/snake.py", line 164, in __getitem__
    img, instance_polys, cls_ids = self.read_original_data(anno, path)
  File "/home/aaronace/Downloads/snake-1/lib/datasets/voc/snake.py", line 32, in read_original_data
    instance_polys = [[np.array(poly).reshape(-1, 2) for poly in obj['segmentation']] for obj in anno]
  File "/home/aaronace/Downloads/snake-1/lib/datasets/voc/snake.py", line 32, in <listcomp>
    instance_polys = [[np.array(poly).reshape(-1, 2) for poly in obj['segmentation']] for obj in anno]
KeyError: 'segmentation'

我遇到这样的问题，我上网爬文，发现好像是network的问题，但是错误的地方又不是在network的地方，请问要怎么修正？

**Comment by Aaron-Ace** [comment]
我现在是利用MVTec Screws Dataset作为训练的资料集
https://www.mvtec.com/company/research/datasets/mvtec-screws/

**Comment by pengsida** [comment]
你这个数据标注格式不是coco的格式，所以有问题。

**Comment by Aaron-Ace** [comment]
請問可以跟我說明一下jsonjson的內容格式嗎？因為文件太大我開啟之後，無法完整查看檔案格式

**Comment by pengsida** [comment]
https://zhuanlan.zhihu.com/p/29393415

**Comment by Aaron-Ace** [comment]
THX!
