### ISSUE TITLE
from lib.csrc.dcn_v2 import _ext as _backend

### ISSUE THREAD

**Issue by naveenkk944** [zju3dv/snake#123]
error from the above line that is 
Traceback (most recent call last):
  File "C:\Users\Naveen Kumar k\Desktop\Project1\snake-master\run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "C:\Users\Naveen Kumar k\Desktop\Project1\snake-master\run.py", line 51, in run_evaluate
    network = make_network(cfg).cuda()
  File "C:\Users\Naveen Kumar k\Desktop\Project1\snake-master\lib\networks\make_network.py", line 23, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "C:\Users\Naveen Kumar k\AppData\Local\Programs\Python\Python37\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/networks\rcnn_snake\__init__.py", line 1, in <module>
    from .ct_rcnn_snake import get_network as get_rcnn
  File "lib/networks\rcnn_snake\ct_rcnn_snake.py", line 2, in <module>
    from .dla import DLASeg
  File "lib/networks\rcnn_snake\dla.py", line 16, in <module>
    from lib.networks.dcn_v2 import DCN
  File "C:\Users\Naveen Kumar k\Desktop\Project1\snake-master\lib\networks\dcn_v2.py", line 13, in <module>
    from lib.csrc.dcn_v2 import _ext as _backend
ImportError: cannot import name '_ext' from 'lib.csrc.dcn_v2' (C:\Users\Naveen Kumar k\Desktop\Project1\snake-master\lib\csrc\dcn_v2\__init__.py)

**Comment by naveenkk944** [comment]
can you please help me to overcome this

**Comment by pengsida** [comment]
You need to compile the code.
![image](https://user-images.githubusercontent.com/11582122/102429066-6d93e300-404d-11eb-9c77-5638c40bc008.png)

**Comment by etasnadi** [comment]
@pengsida Hi, I have a similar issue: `ImportError: cannot import name '_ext' from 'lib.csrc.dcn_v2` when I call `run.py` and trired to compile the dcnv2 based on you suggestion but I get the following error during the compilation:

```snake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.cu(107): error: identifier "THCState_getCurrentStream" is undefined

snake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.cu(126): error: identifier "THCudaBlas_SgemmBatched" is undefined

snake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.cu(273): error: identifier "THCudaBlas_Sgemm" is undefined

snake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.cu(279): error: identifier "THCState_getCurrentStream" is undefined

snake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.cu(324): error: identifier "THCudaBlas_Sgemv" is undefined```

I am using `nvcc 10.1, V10.1.243` and `gcc/g++ 8.4.0` with `torch 1.8.1`.

**Comment by etasnadi** [comment]
Downgraded to torch 1.5 and now only the `THCState_getCurrentStream` is undefined so this should be a torch version mismatch.
