### ISSUE TITLE
A question about train

### ISSUE THREAD

**Issue by YYYyangyiyao** [zju3dv/snake#134]
您好，我在训练的时候，遇到如下问题：
python train_net.py --cfg_file configs/city_ct_rcnn.yaml model rcnn_det
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 46, in main
    network = make_network(cfg)
  File "/home/ncuer/Pycode/snake/lib/networks/make_network.py", line 23, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "/home/ncuer/anaconda3/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/networks/ct_rcnn/__init__.py", line 1, in <module>
    from .ct_rcnn import get_network as get_rcnn
  File "lib/networks/ct_rcnn/ct_rcnn.py", line 2, in <module>
    from .dla import DLASeg
  File "lib/networks/ct_rcnn/dla.py", line 16, in <module>
    from lib.networks.dcn_v2 import DCN
  File "/home/ncuer/Pycode/snake/lib/networks/dcn_v2.py", line 13, in <module>
    from lib.csrc.dcn_v2 import _ext as _backend
ImportError: /home/ncuer/Pycode/snake/lib/csrc/dcn_v2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

我编译了那三个文件，没有报错：
cd /home/ncuer/Pycode/snake/lib/csrc
(base):~/Pycode/snake/lib/csrc$ export CUDA_HOME="/usr/local/cuda-10.0"
(base) :~/Pycode/snake/lib/csrc$ cd dcn_v2
(base) :~/Pycode/snake/lib/csrc/dcn_v2$ python setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-3.7/_ext.cpython-37m-x86_64-linux-gnu.so -> 
(base) :~/Pycode/snake/lib/csrc/dcn_v2$ cd ../extreme_utils
(base):~/Pycode/snake/lib/csrc/extreme_utils$ python setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-3.7/_ext.cpython-37m-x86_64-linux-gnu.so -> 
(base) :~/Pycode/snake/lib/csrc/extreme_utils$ cd ../roi_align_layer
(base) :~/Pycode/snake/lib/csrc/roi_align_layer$ python setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-3.7/_roi_align.cpython-37m-x86_64-linux-gnu.so ->

**Comment by pengsida** [comment]
ImportError: /home/ncuer/Pycode/snake/lib/csrc/dcn_v2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

你的系统cuda和pytorch cuda版本不一致

**Comment by YYYyangyiyao** [comment]
nvcc --v   Cuda compilation tools, release 10.0, V10.0.130
torch.version.cuda  '10.0.130'
torch.__version__ '1.0.1.post2'
torchvision.__version__  '0.2.2'

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/32
https://github.com/zju3dv/snake/issues/26
