### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modiied by an inplace operation

### ISSUE THREAD

**Issue by Fool-hash** [zju3dv/snake#137]
你好，我在运行python train_net.py --cfg_ file configs/sbd_snake.yaml model sbd_snake这句话的时候出现了这个错误，具体信息如下：
file configs/sbd_snake.yaml model sbd_snake
loading annotations into memory...
Done (t=0.14s)
creating index...
index created!
WARNING: NO MODEL LOADED !!!
loading annotations into memory...
Done (t=3.49s)
creating index...
index created!
loading annotations into memory...
Done (t=3.40s)
creating index...
index created!
/home/disk6T/wangchao/.conda/envs/deepsnake/lib/python3.6/site-packages/torch/nn/                                                                                                         parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, bu                                                                                                         t all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/disk6T/wangchao/snake-master/lib/train/trainers/trainer.py", line 4                                                                                                         3, in train
    loss.backward()
  File "/home/disk6T/wangchao/.conda/envs/deepsnake/lib/python3.6/site-packages/t                                                                                                         orch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/disk6T/wangchao/.conda/envs/deepsnake/lib/python3.6/site-packages/t                                                                                                         orch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modif                                                                                                         ied by an inplace operation
我的sbd数据库直接放在了data中
请问这要怎么解决？

**Comment by pengsida** [comment]
你pytorch版本是多少

**Comment by Fool-hash** [comment]
> 你pytorch版本是多少
torch 1.0.1.post2

**Comment by pengsida** [comment]
我没遇到过这样的问题。

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/98

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/50

**Comment by pengsida** [comment]
用pytorch 1.1.0。
![image](https://user-images.githubusercontent.com/11582122/104162363-72bb3680-542f-11eb-8b6d-36dc23cff119.png)
