### ISSUE TITLE
Run demo error

### ISSUE THREAD

**Issue by jiafanxue** [zju3dv/snake#143]
Hi,

When i run this code in my computer, some errors occurred. Is there a solution?

`
python run.py --type demo --cfg_file configs/sbd_snake.yaml demo_path demo_images/2009_000871.jpg ct_score 0.3
  0%|                                                                               | 0/1 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 95, in run_demo
    demo.demo()
  File "/home/xf/Work/DeepSnake/code/snake/tools/demo.py", line 68, in demo
    output = network(batch['inp'], batch)
  File "/home/xf/Work/DeepSnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 54, in forward
    output, cnn_feature = self.dla(x)
  File "/home/xf/Work/DeepSnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 470, in forward
    x = self.dla_up(x)
  File "/home/xf/Work/DeepSnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 409, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/home/xf/Work/DeepSnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 383, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/xf/Work/DeepSnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 356, in forward
    x = self.conv(x)
  File "/home/xf/Work/DeepSnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xf/Work/DeepSnake/code/snake/lib/networks/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/home/xf/Work/DeepSnake/code/snake/lib/networks/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:425
`

my environment in my PC is:
CUDA-9.0
CUDNN v7.0.5
python3.7.9
gcc version:5.4
RTX2080Ti
torch-1.1.0

I searched some results and found that there may be a problem with the GPU and pytorch version, then i change my enviroment:

CUDA-10.2
CUDNN v8.1
python3.7.9
gcc version:5.4
RTX2080Ti
torch-1.7.0

it still doesn't work!!

Is there a solution?

**Comment by pengsida** [comment]
You need to ensure the torch and computer system have the same cuda version.
Then you need to delete the compiled files and recompile them.
