### ISSUE TITLE
Issue of testing on sbd

### ISSUE THREAD

**Issue by fdiskdc** [zju3dv/snake#152]
When I was testing on sbd , the terminal feedback:
load model: data/model/snake/sbd/149.pth
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 77, in run_visualize
    data_loader = make_data_loader(cfg, is_train=False)
  File "/home/ubuntu/vscode/snake/lib/datasets/make_dataset.py", line 61, in make_data_loader
    dataset = make_dataset(cfg, dataset_name, transforms, is_train)
  File "/home/ubuntu/vscode/snake/lib/datasets/make_dataset.py", line 24, in make_dataset
    dataset = _dataset_factory(data_source, cfg.task)
  File "/home/ubuntu/vscode/snake/lib/datasets/make_dataset.py", line 17, in _dataset_factory
    dataset = imp.load_source(module, path).Dataset
  File "/home/ubuntu/anaconda3/envs/snake/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/datasets/sbd/snake.py", line 1, in <module>
    from ..voc.snake import Dataset
  File "/home/ubuntu/vscode/snake/lib/datasets/voc/snake.py", line 8, in <module>
    from pycocotools.coco import COCO
  File "/home/ubuntu/anaconda3/envs/snake/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/ubuntu/anaconda3/envs/snake/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 199, in init pycocotools._mask
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88
Could you help me?
I have create a soft link 'sbd' in a folder called 'data'
Graphics card:1080ti
Cuda:9.0

**Comment by pengsida** [comment]
It is a problem of coco api.
