### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by gpgzy** [zju3dv/snake#170]
您好，我在复现您的代码的时候，在运行训练的命令后，显示不能读取yml文件，请问您知道是我哪里配置有问题吗？
(snake) gzy@xxxy-SYS-4029GP-TRT:~/snake$ python train_net.py --cfg_file configs/city_ct_rcnn.yaml model rcnn_det
Traceback (most recent call last):
  File "train_net.py", line 1, in <module>
    from lib.config import cfg, args
  File "/media/sda1/dongsuyu/snake/lib/config/__init__.py", line 1, in <module>
    from .config import cfg, args
  File "/media/sda1/dongsuyu/snake/lib/config/config.py", line 109, in <module>
    cfg = make_cfg(args)
  File "/media/sda1/dongsuyu/snake/lib/config/config.py", line 93, in make_cfg
    cfg.merge_from_file(args.cfg_file)
  File "/media/sda1/dongsuyu/snake/lib/config/yacs.py", line 170, in merge_from_file
    cfg = load_cfg(f)
  File "/media/sda1/dongsuyu/snake/lib/config/yacs.py", line 300, in load_cfg
    return _load_cfg_from_file(cfg_file_obj_or_str)
  File "/media/sda1/dongsuyu/snake/lib/config/yacs.py", line 309, in _load_cfg_from_file
    return _load_cfg_from_yaml_str(file_obj.read())
  File "/media/sda1/dongsuyu/snake/lib/config/yacs.py", line 321, in _load_cfg_from_yaml_str
    cfg_as_dict = yaml.safe_load(str_obj)
AttributeError: module 'yaml' has no attribute 'safe_load'

**Comment by pengsida** [comment]
pip install PyYAML==5.3.1

**Comment by gpgzy** [comment]
明白了，非常感谢！
