### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by soolone** [zju3dv/snake#185]
环境：
ubuntu16.04 
2080Ti
cuda 10.1
pytorch 1.7.1
gcc 5.5
您好我在执行编译dcn_v2时执行python setup.py build_ext --inplace命令报错：
Traceback (most recent call last):
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/cgim/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by pengsida** [comment]
你有装ninja吗：pip install ninja。看起来好像是调用ninja报错的。

**Comment by soolone** [comment]
> 你有装ninja吗：pip install ninja。看起来好像是调用ninja报错的。

谢谢，已经解决了，应该是Pytorch的版本过高，可以降低Pytoch版本，或者修改dcn_v2_cuda.cu

**Comment by luoshuifeiyang** [comment]
https://github.com/lbin/DCNv2/tree/pytorch_1.9
去这里面更换自己pytorch对应版本的dcnv2
