### ISSUE TITLE
KeyError:'ct_hm' 是啥意思呀

### ISSUE THREAD

**Issue by singing4you** [zju3dv/snake#189]
作者你好 我在用自制训练集训练，.yaml文件复制了coco的yaml文件，heads那一栏没有改 ，其他参数都对应改了，然后训练的时候报错 
`Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/root/snake-master/lib/train/trainers/trainer.py", line 38, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/snake.py", line 24, in forward
    ct_loss = self.ct_crit(net_utils.sigmoid(output['ct_hm']), batch['ct_hm'])
KeyError: 'ct_hm'
`
请问这是什么原因导致的呢？该怎么修改代码

**Comment by pengsida** [comment]
可能dataset设置有问题。
