### ISSUE TITLE
 cublas runtime error : the GPU program failed to execute

### ISSUE THREAD

**Issue by wujunlan** [zju3dv/snake#190]
您好，我在运行Test on Kitti时（train也一样），出现以下报错：
load model: data/model/snake/kins/149.pth
loading annotations into memory...
Done (t=1.11s)
creating index...
index created!
loading annotations into memory...
Done (t=1.11s)
creating index...
index created!
  0%|                                                                                                                                                                                                    | 0/7517 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 60, in run_evaluate
    output = network(inp)
  File "/home/lan/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 54, in forward
    output, cnn_feature = self.dla(x)
  File "/home/lan/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 470, in forward
    x = self.dla_up(x)
  File "/home/lan/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 409, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/home/lan/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 383, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/lan/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 356, in forward
    x = self.conv(x)
  File "/home/lan/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lan/桌面/snake/lib/networks/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/home/lan/桌面/snake/lib/networks/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:425

以上问题通过更换cuda版本以及pytorch版本均未解决，并更换了电脑在不同显卡上报同样错误，定位到dcn_v2.py下的“from lib.csrc.dcn_v2 import _ext as _backend”报错，但是已经进行了
cd dcn_v2
python setup.py build_ext --inplace
步骤，这是什么原因呢？

**Comment by pengsida** [comment]
重新编译之前需要把之前编译的内容删除。

**Comment by wujunlan** [comment]
是删除了重新编译的，刚刚又试了一遍，还是有：
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:425
我去搜索了[https://github.com/CharlesShang/DCNv2](url)
在运行    python testcuda.py  也有同样问题，但没找到解决方法。请问您之前遇到过类似问题么？有没有什么建议？

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/94
