### ISSUE TITLE
训练kitti数据集时报错：storage has wrong size: expected 0 got 256

### ISSUE THREAD

**Issue by singing4you** [zju3dv/snake#191]
作者你好,我按照install.md安装好了环境,下载了kitti数据集 训练集的位置是 /root/snake-master/data/kitti/training
测试集的位置是 /root/snake-master/data/kitti/testing    然后我执行命令
`python train_net.py --cfg_file configs/kins_snake.yaml model kins_snake`
然后就报错：
`(base) root@40adaf20387b:~/snake-master# python train_net.py --cfg_file configs/kins_snake.yaml model kins_snake
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 46, in main
    network = make_network(cfg)
  File "/root/snake-master/lib/networks/make_network.py", line 23, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "lib/networks/snake/__init__.py", line 17, in get_network
    network = get_model(num_layers, heads, head_conv, snake_config.down_ratio, cfg.det_dir)
  File "lib/networks/snake/ct_snake.py", line 64, in get_network
    network = Network(num_layers, heads, head_conv, down_ratio, det_dir)
  File "lib/networks/snake/ct_snake.py", line 19, in __init__
    head_conv=head_conv)
  File "lib/networks/snake/dla.py", line 432, in __init__
    self.base = globals()[base_name](pretrained=pretrained)
  File "lib/networks/snake/dla.py", line 315, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "lib/networks/snake/dla.py", line 301, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/hub.py", line 506, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 256
`
我没有改过代码，请问该怎么办呀。还有执行命令的时候会自动下载dla34-ba72cf86.pth ，下载这个是必须的吗

**Comment by pengsida** [comment]
这个下载是必须的。

**Comment by singing4you** [comment]
> 这个下载是必须的。

好的，谢谢作者！    还有就是我的训练集图片的位置是根据`dataset_catalog.py` 文件中  `’KinsTrain‘那一项` 放在`/root/snake-master/data/kitti/training/image_2` 目录下， 而没有像install.md要求的放到path/to/kitti/training/image_2 目录下， 请问我放的位置是对的吗
![image](https://user-images.githubusercontent.com/56928566/129466064-32f87d3a-02e4-4cf5-bced-4eedbef2e5d0.png)

**Comment by singing4you** [comment]
> 这个下载是必须的。

谢谢！ 我已经解决的 应该是pytorch版本的问题，我换到pytorch 1.1版本就没报错了
