### ISSUE TITLE
cuda runtime error (9) : invalid configuration argument at /snake/lib/csrc/extreme_utils/src/utils.cu:299

### ISSUE THREAD

**Issue by TengFeiHan0** [zju3dv/snake#21]
I have trained your model successfully yesterday, Now I'm working on testing my obtained model on cityscapes. However, No matter how I tried,  a CUDA error always exists. I'm not familiar with CUDA programming, so I have to open an issue to trouble you @pengsida   Have you ever encounter this kind of problem? thank you in advance.
```
loading annotations into memory...
Done (t=0.17s)
creating index...
index created!
loading annotations into memory...
Done (t=0.14s)
creating index...
index created!
  0%|                                                             | 0/492 [00:00<?, ?it/s]THCudaCheck FAIL file=/home/fei/snake/lib/csrc/extreme_utils/src/utils.cu line=299 error=9 : invalid configuration argument

Traceback (most recent call last):
  File "run.py", line 89, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 60, in run_evaluate
    output = network(inp)
  File "/home/fei/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/rcnn_snake/ct_rcnn_snake.py", line 42, in forward
    output = self.gcn(output, cnn_feature, batch)
  File "/home/fei/anaconda3/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/rcnn_snake/evolve.py", line 111, in forward
    init = self.prepare_testing_init(output)
  File "lib/networks/rcnn_snake/evolve.py", line 41, in prepare_testing_init
    i_it_4py = snake_gcn_utils.uniform_upsample(i_it_4py, snake_config.init_poly_num)
  File "/home/fei/snake/lib/utils/snake/snake_gcn_utils.py", line 226, in uniform_upsample
    extreme_utils.calculate_edge_num(edge_num, edge_num_sum, edge_idx_sort, p_num)
RuntimeError: cuda runtime error (9) : invalid configuration argument at /home/fei/snake/lib/csrc/extreme_utils/src/utils.cu:299
```

**Comment by pengsida** [comment]
What is your command?
If you did not load the pretrained model, you probably encounter this problem.

**Comment by TengFeiHan0** [comment]
I'm so sorry to ask such a naive question, I already fix it, thanks for your quick response.  The reason is I forgot to add `model rcnn_snake` option.

**Comment by pengsida** [comment]
I have updated the code, which will give a warning message if the model is not loaded successfully.
Note that the option `model model_name` means the name of your pretrained model. You might need to provide a new name for your own model.
