### ISSUE TITLE
ImportError: cannot import name '_ext' from 'lib.csrc.dcn_v2'

### ISSUE THREAD

**Issue by tony71200** [zju3dv/snake#217]
I'm the newbie.
I have a problem when run demo file.

Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 95, in run_demo
    demo.demo()
  File "D:\02_BME\snake\tools\demo.py", line 59, in demo
    network = make_network(cfg).cuda()
  File "D:\02_BME\snake\lib\networks\make_network.py", line 24, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "C:\Users\tony10200\anaconda3\envs\scaled_yolo\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/networks\snake\__init__.py", line 2, in <module>
    from .ct_snake import get_network as get_ro
  File "lib/networks\snake\ct_snake.py", line 2, in <module>
    from .dla import DLASeg
  File "lib/networks\snake\dla.py", line 16, in <module>
    from lib.networks.dcn_v2 import DCN
  File "D:\02_BME\snake\lib\networks\dcn_v2.py", line 13, in <module>
    from lib.csrc.dcn_v2 import _ext as _backend
ImportError: cannot import name '_ext' from 'lib.csrc.dcn_v2' (D:\02_BME\snake\lib\csrc\dcn_v2\__init__.py)

I hope you can help me

**Comment by pengsida** [comment]
Please compile the code.

![image](https://user-images.githubusercontent.com/11582122/151951167-360edd8a-a27e-475d-b024-daaf2a753ec9.png)
