### ISSUE TITLE
Dimension not match in _neg_loss(pred, gt)

### ISSUE THREAD

**Issue by RonDen** [zju3dv/snake#44]
Why was this happend ?

```
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/train/trainers/trainer.py", line 38, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/snake.py", line 24, in forward
    ct_loss = self.ct_crit(net_utils.sigmoid(output['ct_hm']), batch['ct_hm'])
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/utils/net_utils.py", line 50, in forward
    return self.neg_loss(out, target)
  File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/utils/net_utils.py", line 29, in _neg_loss
    pos_loss = torch.log(pred) * torch.pow(1 - pred, 2) * pos_inds
RuntimeError: The size of tensor a (20) must match the size of tensor b (80) at non-singleton dimension 1
```

How to reproduce:

I used the COCO format dataset. And run:
```bash
python train_net.py --cfg_file configs/sbd_snake.yaml model custom_model train.dataset CocoTrain test.dataset CocoVal
```

**Comment by pengsida** [comment]
The number of classes in `sbd_snake.yaml` is set to 20 https://github.com/zju3dv/snake/blob/master/configs/sbd_snake.yaml#L20, while the class number is set to 80 in Coco dataset https://github.com/zju3dv/snake/blob/master/lib/datasets/coco/snake.py#L151

**Comment by RonDen** [comment]
Got it! Thank you!

**Comment by RonDen** [comment]
Maybe there should be a variable `num_class` to control this.

**Comment by pengsida** [comment]
It is a good advice.
I have updated the code.

**Comment by RonDen** [comment]
I constantly get this error in almost every 4-5 epoch training.
```bash
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 35, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/train/trainers/trainer.py", line 76, in val
    for batch in tqdm.tqdm(data_loader):
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/datasets/collate_batch.py", line 7, in snake_collator
    ret = {'inp': default_collate([b['inp'] for b in batch])}
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 65, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 544 and 480 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:689
```

Should the  validation dataloader worker number be set as 0?
Previously, I got this error in train dataloader, so I set the num_worker=0, it works.

Configuration as follow:
```yaml
train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120, 150, 170)
    gamma: 0.5
    batch_size: 16
    dataset: 'CocoTrain'
    num_workers: 0
    epoch: 150
test:
    # dataset: 'SbdMini'
    dataset: 'CocoVal'
    batch_size: 16
    num_workers: 0
```

My operating system is Ubuntu16.04.
Thank you!
