### ISSUE TITLE
RuntimeError: error executing torch_shm_manager

### ISSUE THREAD

**Issue by wqtwjt1996** [zju3dv/snake#47]
After I finished the setting from your INSTALL.md and when I ran the testing code:

python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml test.dataset CityscapesVal

I saw these errors:

WARNING: NO MODEL LOADED !!!
load model: data/model/rcnn_snake/long_rcnn/197.pth
  0%|                                                   | 0/492 [00:00<?, ?it/s]torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 57, in run_evaluate
    for batch in tqdm.tqdm(data_loader):
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1119, in __iter__
    for obj in iterable:
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/andrew/Documents/snake-master/lib/datasets/collate_batch.py", line 94, in rcnn_snake_collator
    ret = {'inp': default_collate([b['inp'] for b in batch])}
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "/home/andrew/anaconda3/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at /pytorch/torch/lib/libshm/core.cpp:99

torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
torch_shm_managertorch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
  0%|                                                   | 0/492 [00:01<?, ?it/s]

**My environment are as fellows:
Pytorch: 1.4.0
Torchvision: 0.5.0
Ubuntu: 18.04.2
CUDA version(from "torch.version.cuda"): 10.1**

And I have already checked the path of your pretrained model, which is $ROOT/data/model/rcnn_snake/long_rcnn/197.pth

So could you please help me to figure out what is going on? I would be very honored if you can help me!

Thanks!

**Comment by pengsida** [comment]
The model is loaded, as indicated by `load model: data/model/rcnn_snake/long_rcnn/197.pth`.
You problem might be caused by either pytorch version or cuda version: https://github.com/MVIG-SJTU/AlphaPose/issues/402
