### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Ruanyuzhe** [zju3dv/snake#50]
笔者你好，今天将代码在Kins上运行，出现如下错误，不知道问题出在哪

index created!
/home/mil/ruan/.pyenv/versions/anaconda3-2019.07/envs/snake1/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/mil/ruan/home/mil/ruan/snake/snake-master/lib/train/trainers/trainer.py", line 43, in train
    loss.backward()
  File "/home/mil/ruan/.pyenv/versions/anaconda3-2019.07/envs/snake1/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/mil/ruan/.pyenv/versions/anaconda3-2019.07/envs/snake1/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

**Comment by pengsida** [comment]
你有改过代码吗

**Comment by Ruanyuzhe** [comment]
我没有改过代码

**Comment by Ruanyuzhe** [comment]
我的问题解决了。好像是pytorch版本的问题
