### ISSUE TITLE
RuntimeError: cublas runtime error

### ISSUE THREAD

**Issue by Nephiloso** [zju3dv/snake#77]
Hi. When I try to test the model on Cityscapes, it gives an error:

WARNING: NO MODEL LOADED !!!
load model: data/model/rcnn_snake/long_rcnn/197.pth
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
loading annotations into memory...
Done (t=0.19s)
creating index...
index created!
  0%|                                                                                                                          | 0/492 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 60, in run_evaluate
    output = network(inp)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/rcnn_snake/ct_rcnn_snake.py", line 38, in forward
    output, cnn_feature = self.dla(x)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/rcnn_snake/dla.py", line 470, in forward
    x = self.dla_up(x)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/rcnn_snake/dla.py", line 409, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/rcnn_snake/dla.py", line 383, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/rcnn_snake/dla.py", line 356, in forward
    x = self.conv(x)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/GPFS/liying_lab_permanent/liang/deepSnake/snake/lib/networks/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/GPFS/liying_lab_permanent/liang/deepSnake/snake/lib/networks/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:425

At first, I thought it is the same problem as [this issue](https://github.com/zju3dv/snake/issues/66) that the model can't read the .json file. But I checked and found that the .json of the Cityscape could be loaded.
Then I tried to run the demo, and saw the same error:

WARNING: NO MODEL LOADED !!!
  0%|                                                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 95, in run_demo
    demo.demo()
  File "/GPFS/liying_lab_permanent/liang/deepSnake/snake/tools/demo.py", line 68, in demo
    output = network(batch['inp'], batch)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/ct_snake.py", line 54, in forward
    output, cnn_feature = self.dla(x)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 470, in forward
    x = self.dla_up(x)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 409, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 383, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/snake/dla.py", line 356, in forward
    x = self.conv(x)
  File "/home/liying_lab/liang/.conda/envs/deepsnake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/GPFS/liying_lab_permanent/liang/deepSnake/snake/lib/networks/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/GPFS/liying_lab_permanent/liang/deepSnake/snake/lib/networks/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:425

My environment:
pytorch 1.1.0
CUDA: 9.1

Could you help me figure out what's going on? Thanks.

**Comment by pengsida** [comment]
Sorry for late reply.
Is your gpu a RTX card?

**Comment by Nephiloso** [comment]
I don't think so. It's NVIDIA Tesla V100-SXM2.

**Comment by pengsida** [comment]
Have you run other pytorch code on your computer environment?

**Comment by Nephiloso** [comment]
I tried a neural network toy model with cuda and it worked. Do I have to use RTX card?

**Comment by pengsida** [comment]
No, you do not need a RTX card.
I googled and found that some related problems are caused by the gpu type: https://github.com/pytorch/pytorch/issues/17334

**Comment by Nephiloso** [comment]
Hi. I just figured out the issue. I might because of the version of PyTorch. Just install it using anaconda instead of pip could solve the problem: `conda install pytorch torchvision cudatookit=9.0 -c pytorch`

**Comment by fh2019ustc** [comment]
@Nephiloso I have the same error as yours. My card is RTX2080ti. Then I change the card to 1080ti, it can run.
