### ISSUE TITLE
Problem while using pretrained model to train my own dataset

### ISSUE THREAD

**Issue by Nephiloso** [zju3dv/snake#90]
Hi. I want to use your pretrained model to train my own dataset. And there's an error said:

```
$ python train_net.py --cfg_file configs/mouse_snake.yaml model sbd_snake
loading annotations into memory...
Done (t=0.27s)
creating index...
index created!
data/model/snake/sbd_snake
load model: data/model/snake/sbd_snake/149.pth
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 17, in train
    begin_epoch = load_model(network, optimizer, scheduler, recorder, cfg.model_dir, resume=cfg.resume)
  File "/DATA/wupx/snake/lib/utils/net_utils.py", line 287, in load_model
    optim.load_state_dict(pretrained_model['optim'])
KeyError: 'optim'
```

Then I found that the pretrained model has only two keys:
```
print(pretrained_model.keys())
dict_keys(['net', 'epoch'])
```

I have made a yaml file about my configuration which contains optimization and number of epoch. Shall I just command the [relevant lines](https://github.com/zju3dv/snake/blob/master/lib/utils/net_utils.py#L286-L288) out in net_utils.py? Thank you so much.

**Comment by pengsida** [comment]
Yes.

**Comment by Nephiloso** [comment]
Got it. Thanks.
