### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by wangshuo2020** [zju3dv/snake#92]
Warning: Torch did not find available GPUs on this system.
 If your intention is to cross-compile, this is not an error.

torch.__version__  =  1.1.0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-9.0'

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
from /usr/local/cuda-9.0/bin

Pytorch binaries were compiled with Cuda 9.0.176

running install
running bdist_egg
running egg_info
writing apex.egg-info/PKG-INFO
writing dependency_links to apex.egg-info/dependency_links.txt
writing top-level names to apex.egg-info/top_level.txt
reading manifest file 'apex.egg-info/SOURCES.txt'
writing manifest file 'apex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'fused_adam_cuda' extension
gcc -pthread -B /home/ws/anaconda3/envs/snake_v2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/include -I/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/include/TH -I/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/ws/anaconda3/envs/snake_v2/include/python3.7m -c csrc/fused_adam_cuda.cpp -o build/temp.linux-x86_64-3.7/csrc/fused_adam_cuda.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=fused_adam_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1

~~~~~
(snake_v2) ws@ws-OMEN-Laptop-15-ek0xxx:~/apex$ python -c "import torch; print(torch.version.cuda)"
9.0.176
(snake_v2) ws@ws-OMEN-Laptop-15-ek0xxx:~/apex$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by wangshuo2020** [comment]
上面的error解决了 error: command 'gcc' failed with exit status 1 但是还存在这个问题
~~~
snake_v2) ws@ws-OMEN-Laptop-15-ek0xxx:~/snake/lib/csrc/dcn_v2$ python setup.py build_ext --inplace
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-9.0'
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 41, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

**Comment by wangshuo2020** [comment]
~~~
ws@ws-OMEN-Laptop-15-ek0xxx:/usr/local/cuda-9.0/samples/1_Utilities/deviceQuery$ sudo ./deviceQuery 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce RTX 2060"
  CUDA Driver Version / Runtime Version          11.0 / 9.0
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 5935 MBytes (6222839808 bytes)
MapSMtoCores for SM 7.5 is undefined.  Default to use 64 Cores/SM
MapSMtoCores for SM 7.5 is undefined.  Default to use 64 Cores/SM
  (30) Multiprocessors, ( 64) CUDA Cores/MP:     1920 CUDA Cores
  GPU Max Clock rate:                            1200 MHz (1.20 GHz)
  Memory Clock rate:                             5501 Mhz
  Memory Bus Width:                              192-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.0, CUDA Runtime Version = 9.0, NumDevs = 1

**Comment by wangshuo2020** [comment]
去验证了下cuda的确安装成功了 再执行就没报错了 不知道为啥
