### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/coco_ann/instance_val.json'

### ISSUE THREAD

**Issue by wangshuo2020** [zju3dv/snake#93]
~~~
(snake_v2) ws@ws-OMEN-Laptop-15-ek0xxx:~/snake$ python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml
WARNING: NO MODEL LOADED !!!
load model: data/model/rcnn_snake/long_rcnn/197.pth
loading annotations into memory...
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 55, in run_evaluate
    data_loader = make_data_loader(cfg, is_train=False)
  File "/home/ws/snake/lib/datasets/make_dataset.py", line 61, in make_data_loader
    dataset = make_dataset(cfg, dataset_name, transforms, is_train)
  File "/home/ws/snake/lib/datasets/make_dataset.py", line 29, in make_dataset
    dataset = dataset(**args)
  File "lib/datasets/cityscapes_coco/rcnn_snake.py", line 20, in __init__
    self.coco = COCO(ann_file)
  File "/home/ws/anaconda3/envs/snake_v2/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/coco_ann/instance_val.json'

**Comment by wangshuo2020** [comment]
~~~
我下载了模型 把模型放在了相应的位置 $ROOT/data/model/rcnn_snake/long_rcnn/197.pth
# use coco evaluator
python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml
在执行这个命令的时候报了上面的错误
